repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict


  # python code analysis
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length=120",
               "--ignore", " ",
               ]

  # python linting
  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        name: pylint
        entry: pylint # --score=no
        language: system
        types: [python]
        args: ["--disable", "missing-module-docstring, missing-function-docstring, too-many-locals, unused-variable",
               "--max-line-length", "120",
               "--extension-pkg-whitelist", "cv2",
               "--ignored-modules", "cv2",
               "--good-names", "e, i, id, x, y, df, y1, y2, x1, x2, j" ]

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        #args: ["--ignore", "DL3008"]
