# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ready_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
            self.video_list = []
            self.cur_video = None
            self.cur_video_num = None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 698)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_view = QtWidgets.QListWidget(self.centralwidget)
        self.list_view.setGeometry(QtCore.QRect(0, 30, 281, 661))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_view.setFont(font)
        self.list_view.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.list_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_view.setStyleSheet(
                "QListView{\n"
                "    background-color: rgb(192, 191, 188);\n"
                "    border-color: rgb(0, 0, 0);\n"
                "    border-style: solid;\n"
                "    border-width: 1px;\n"
                "    padding: 5px;\n"
                "    padding-left: 5px;\n"
                "}\n"
                "\n"
                "QListView:item{\n"
                "    border: 2px solid black;\n"
                "    margin:5px;\n"
                "    height:60px;\n"
                "    width:240px;\n"
                "}\n"
                "\n"
                "QListView:item:selected{\n"
                "    border: 1px solid black;\n"
                "    background-color: rgba(255, 120, 0, 171);\n"
                "}")
        self.list_view.setAutoScroll(True)
        self.list_view.setMovement(QtWidgets.QListView.Static)
        self.list_view.setFlow(QtWidgets.QListView.LeftToRight)
        self.list_view.setProperty("isWrapping", True)
        self.list_view.setResizeMode(QtWidgets.QListView.Fixed)
        self.list_view.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list_view.setGridSize(QtCore.QSize(200, 70))
        self.list_view.setViewMode(QtWidgets.QListView.ListMode)
        self.list_view.setModelColumn(0)
        self.list_view.setUniformItemSizes(False)
        self.list_view.setWordWrap(False)
        self.list_view.setSelectionRectVisible(True)
        self.list_view.setObjectName("list_view")
        self.l_videos = QtWidgets.QLabel(self.centralwidget)
        self.l_videos.setGeometry(QtCore.QRect(0, 0, 281, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.l_videos.setFont(font)
        self.l_videos.setStyleSheet(
                "background-color: rgb(255, 120, 0);\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-style: solid;\n"
                "border-width: 1px;")
        self.l_videos.setAlignment(QtCore.Qt.AlignCenter)
        self.l_videos.setObjectName("l_videos")
        self.l_preview = QtWidgets.QLabel(self.centralwidget)
        self.l_preview.setGeometry(QtCore.QRect(340, 30, 901, 491))
        self.l_preview.setStyleSheet(
                "background-color: rgb(192, 191, 188);\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-style: solid;\n"
                "border-width: 1px;")
        self.l_preview.setText("")
        self.l_preview.setObjectName("l_preview")
        self.btn_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyze.setEnabled(False)
        self.btn_analyze.setGeometry(QtCore.QRect(340, 540, 591, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btn_analyze.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_analyze.setFont(font)
        self.btn_analyze.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_analyze.setStyleSheet(
                "QPushButton {\n"
                "    border-radius: 40px;\n"
                "    background-color: rgb(255, 120, 0);\n"
                "    border-style: solid;\n"
                "    border-width: 1px;\n"
                "    border-color: rgb(0, 0, 0);\n"
                "}\n"
                "\n"
                "QPushButton:disabled {\n"
                "    background-color: rgb(192, 191, 188);\n"
                "    color: rgb(0, 0, 0);\n"
                "}\n"
                "\n"
                "QPushButton:hover {\n"
                "    background-color: qlineargradient(spread:reflect, x1:0.493, y1:0.488545, x2:1, y2:1, stop:0.189055 rgba(255, 120, 0, 255), stop:1 rgba(255, 232, 214, 255));\n"
                "}")
        self.btn_analyze.setObjectName("btn_analyze")
        self.btn_prev = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prev.setEnabled(False)
        self.btn_prev.setGeometry(QtCore.QRect(940, 540, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_prev.setFont(font)
        self.btn_prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev.setStyleSheet(
                "QPushButton {\n"
                "    border-radius: 40px;\n"
                "    background-color: rgb(255, 120, 0);\n"
                "    border-style: solid;\n"
                "    border-width: 1px;\n"
                "    border-color: rgb(0, 0, 0);\n"
                "}\n"
                "\n"
                "QPushButton:disabled {\n"
                "    background-color: rgb(192, 191, 188);\n"
                "    color: rgb(0, 0, 0);\n"
                "}\n"
                "\n"
                "QPushButton:hover {\n"
                "    background-color: qlineargradient(spread:reflect, x1:0.493, y1:0.488545, x2:1, y2:1, stop:0.189055 rgba(255, 120, 0, 255), stop:1 rgba(255, 232, 214, 255));\n"
                "}")
        self.btn_prev.setObjectName("btn_prev")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setEnabled(False)
        self.progress_bar.setGeometry(QtCore.QRect(340, 640, 901, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 191, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.progress_bar.setPalette(palette)
        self.progress_bar.setStyleSheet(
                "QProgressBar {\n"
                "    background-color: rgb(192, 191, 188);\n"
                "    border: 2px solid grey;\n"
                "    border-radius: 10px;\n"
                "    text-align: center;\n"
                "    padding-left:4px;\n"
                "    padding-right:4px;\n"
                "}\n"
                "\n"
                "QProgressBar:chunk {\n"
                "    background-color: rgb(255, 120, 0);\n"
                "    width: 10px;\n"
                "    margin: 1px;\n"
                "}\n"
                "\n"
                "QProgressBar:disabled {\n"
                "    background-color: rgb(239, 239, 239);\n"
                "    border: 2px solid rgb(239, 239, 239);\n"
                "    color: rgb(239, 239, 239);\n"
                "}\n"
                "")
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setObjectName("progress_bar")
        self.l_videoname = QtWidgets.QLabel(self.centralwidget)
        self.l_videoname.setGeometry(QtCore.QRect(350, 7, 881, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_videoname.setFont(font)
        self.l_videoname.setText("")
        self.l_videoname.setAlignment(QtCore.Qt.AlignCenter)
        self.l_videoname.setObjectName("l_videoname")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.list_view.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.my_setup_ui()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video analysis of passersby"))
        self.list_view.setSortingEnabled(False)
        self.l_videos.setText(_translate("MainWindow", "Videos"))
        self.btn_analyze.setText(_translate("MainWindow", "Analyze"))
        self.btn_prev.setText(_translate("MainWindow", "Show previous analysis"))

    def my_setup_ui(self):
        self.get_video_list()
        video_icon = QtGui.QIcon('video_icon.png')
        for video in self.video_list:
            item = QtWidgets.QListWidgetItem(video_icon, video)
            self.list_view.addItem(item)

        self.list_view.currentRowChanged.connect(self.currentRowChanged_handler)

    def get_video_list(self):
        videos_dir = 'videos/'
        for file in os.listdir(videos_dir):
            ext = os.path.splitext(videos_dir + file)[1]
            if ext != '.mkv' and ext != '.mp4':
                continue
            else:
                self.video_list.append(file)

    def currentRowChanged_handler(self):
        self.cur_video_num = self.list_view.currentRow()
        self.cur_video = self.list_view.currentItem().text()

        self.l_videoname.setText(self.cur_video)
        self.btn_analyze.setEnabled(True)
        self.btn_prev.setEnabled(True)






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
