# Form implementation generated from reading ui file 'target_analysis_main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TargetMain(object):
    def __init__(self, item_index, emotion_index):
        self.item_index = item_index
        self.emotion_index = emotion_index

        self.item_dict = {
            0: 'Рюкзак',
            1: 'Зонт',
            2: 'Сумка',
            3: 'Чемодан',
            4: 'Бейсбольная бита',
            5: 'Скейтборд',
            6: 'Бутылка',
            7: 'Нож',
            8: 'Ноутбук',
            9: 'Телефон',
            10: 'Книга',
            11: 'Ножницы'
        }

        self.emotion_dict = {
            0: 'Злость',
            1: 'Грусть',
            2: 'Испуг',
            3: 'Отвращение',
            4: 'Радость',
            5: 'Удивление',
            6: 'Презрение',
            7: 'Нейтрально'
        }

        self.target_type = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 469)
        MainWindow.setFixedWidth(760)
        MainWindow.setFixedHeight(469)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_persons = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_persons.setGeometry(QtCore.QRect(10, 40, 201, 31))
        self.label_persons.setStyleSheet("background-color: rgb(255, 120, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;")
        self.label_persons.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_persons.setObjectName("label_persons")
        self.list_view_persons = QtWidgets.QListWidget(parent=self.centralwidget)
        self.list_view_persons.setEnabled(True)
        self.list_view_persons.setGeometry(QtCore.QRect(10, 70, 201, 391))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.list_view_persons.setFont(font)
        self.list_view_persons.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.list_view_persons.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.list_view_persons.setStyleSheet("QListView{\n"
"    background-color: rgb(119, 118, 123);\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    padding: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"}\n"
"\n"
"QListView:item{\n"
"    border: 2px solid black;\n"
"    background-color: rgb(192, 191, 188);\n"
"    margin:6px;\n"
"    height:45px;\n"
"    width:160px;\n"
"}\n"
"\n"
"QListView:item:selected{\n"
"    border: 1px solid black;\n"
"    background-color: rgba(255, 120, 0, 171);\n"
"}")
        self.list_view_persons.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.list_view_persons.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.list_view_persons.setAutoScroll(True)
        self.list_view_persons.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.list_view_persons.setMovement(QtWidgets.QListView.Movement.Static)
        self.list_view_persons.setFlow(QtWidgets.QListView.Flow.LeftToRight)
        self.list_view_persons.setProperty("isWrapping", True)
        self.list_view_persons.setResizeMode(QtWidgets.QListView.ResizeMode.Fixed)
        self.list_view_persons.setLayoutMode(QtWidgets.QListView.LayoutMode.SinglePass)
        self.list_view_persons.setGridSize(QtCore.QSize(120, 53))
        self.list_view_persons.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.list_view_persons.setModelColumn(0)
        self.list_view_persons.setUniformItemSizes(False)
        self.list_view_persons.setWordWrap(False)
        self.list_view_persons.setSelectionRectVisible(True)
        self.list_view_persons.setObjectName("list_view_persons")
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_view_persons.addItem(item)
        self.label_target_type = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_target_type.setGeometry(QtCore.QRect(0, 0, 753, 31))
        self.label_target_type.setStyleSheet("background-color: rgb(255, 120, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;")
        self.label_target_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_target_type.setObjectName("label_target_type")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 39, 541, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.label_time = QtWidgets.QLabel(parent=self.page_main)
        self.label_time.setGeometry(QtCore.QRect(300, 390, 241, 30))
        self.label_time.setStyleSheet("background-color: rgba(0, 0, 0, 0.8);\n"
"color: rgb(255, 120, 0);\n"
"padding-left: 5px;")
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.l_photobox = QtWidgets.QLabel(parent=self.page_main)
        self.l_photobox.setGeometry(QtCore.QRect(30, 1, 241, 421))
        self.l_photobox.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.l_photobox.setText("")
        self.l_photobox.setObjectName("l_photobox")
        self.l_item = QtWidgets.QLabel(parent=self.page_main)
        self.l_item.setGeometry(QtCore.QRect(300, 0, 241, 311))
        self.l_item.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.l_item.setText("")
        self.l_item.setObjectName("l_item")
        self.label_conf = QtWidgets.QLabel(parent=self.page_main)
        self.label_conf.setGeometry(QtCore.QRect(300, 360, 241, 30))
        self.label_conf.setStyleSheet("background-color: rgba(0, 0, 0, 0.8);\n"
"color: rgb(255, 120, 0);\n"
"padding-left: 5px;\n"
"")
        self.label_conf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_conf.setObjectName("label_conf")
        self.label_name = QtWidgets.QLabel(parent=self.page_main)
        self.label_name.setGeometry(QtCore.QRect(300, 330, 241, 30))
        self.label_name.setStyleSheet("background-color: rgba(0, 0, 0, 0.8);\n"
"color: rgb(255, 120, 0);\n"
"padding-left: 5px;\n"
"")
        self.label_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.stackedWidget.addWidget(self.page_main)
        self.page_loading = QtWidgets.QWidget()
        self.page_loading.setObjectName("page_loading")
        self.label_loading = QtWidgets.QLabel(parent=self.page_loading)
        self.label_loading.setGeometry(QtCore.QRect(160, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("")
        self.label_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.l_loading = QtWidgets.QLabel(parent=self.page_loading)
        self.l_loading.setGeometry(QtCore.QRect(120, 200, 301, 41))
        self.l_loading.setStyleSheet("")
        self.l_loading.setText("")
        self.l_loading.setObjectName("l_loading")
        self.stackedWidget.addWidget(self.page_loading)
        self.stackedWidget.raise_()
        self.label_persons.raise_()
        self.list_view_persons.raise_()
        self.label_target_type.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.list_view_persons.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.my_setup_ui()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Таргет-анализ"))
        self.label_persons.setText(_translate("MainWindow", "Список людей"))
        self.list_view_persons.setSortingEnabled(False)
        __sortingEnabled = self.list_view_persons.isSortingEnabled()
        self.list_view_persons.setSortingEnabled(False)
        item = self.list_view_persons.item(0)
        item.setText(_translate("MainWindow", "Человек 1"))
        item = self.list_view_persons.item(1)
        item.setText(_translate("MainWindow", "Человек 2"))
        item = self.list_view_persons.item(2)
        item.setText(_translate("MainWindow", "Человек 3"))
        item = self.list_view_persons.item(3)
        item.setText(_translate("MainWindow", "Человек 4"))
        item = self.list_view_persons.item(4)
        item.setText(_translate("MainWindow", "Человек 5"))
        item = self.list_view_persons.item(5)
        item.setText(_translate("MainWindow", "Человек 6"))
        item = self.list_view_persons.item(6)
        item.setText(_translate("MainWindow", "Человек 7"))
        item = self.list_view_persons.item(7)
        item.setText(_translate("MainWindow", "Человек 8"))
        item = self.list_view_persons.item(8)
        item.setText(_translate("MainWindow", "Человек 9"))
        item = self.list_view_persons.item(9)
        item.setText(_translate("MainWindow", "Человек 10"))
        self.list_view_persons.setSortingEnabled(__sortingEnabled)
        self.label_target_type.setText(_translate("MainWindow", "Таргет-анализ эмоций: Злость"))
        self.label_time.setText(_translate("MainWindow", "Время обнаружения: 00:00:00"))
        self.label_conf.setText(_translate("MainWindow", "Уверенность модели: 59%"))
        self.label_name.setText(_translate("MainWindow", "Эмоция: Злость"))
        self.label_loading.setText(_translate("MainWindow", "Загрузка"))

    def my_setup_ui(self):
        if self.emotion_index is not None:
            self.target_type = True
        else:
            self.target_type = False

        if self.target_type:
            self.label_target_type.setText(f'Таргет анализ эмоций: {self.emotion_dict.get(self.emotion_index)}')
        else:
            self.label_target_type.setText(f'Таргет анализ предметов: {self.item_dict.get(self.item_index)}')

        self.list_view_persons.clear()
        self.label_name.clear()
        self.label_conf.clear()
        self.label_time.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TargetMain(0, None)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
